spring: 
  profiles: 
    active: 
    - dev
---

server:
  port: 8001

spring:
  profiles: dev
  application:
    name: ds-sso #eureka微服务列表里显示的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/ds_user              # 数据库名称
    username: root
    password: 151959.0
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ds-dept8001 #在eureka微服务列表里就不会显示主机名
    prefer-ip-address: true     #访问路径可以显示IP地址
    
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true # 配置请求GZIP压缩
      mime-types: ["text/xml","application/xml","application/json"] # 配置压缩支持的MIME TYPE
      min-request-size: 2048 # 配置压缩数据大小的下限
    response:
      enabled: true # 配置响应GZIP压缩

info:
  app.name: mrzhong-ds
  company.name: www.mrzhong.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


---

server:
  port: 8001

spring:
  profiles: test
  application:
    name: ds-sso #eureka微服务列表里显示的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/ds_user              # 数据库名称
    username: root
    password: 151959.0
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ds-dept8001 #在eureka微服务列表里就不会显示主机名
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: mrzhong-ds
  company.name: www.mrzhong.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
