spring: 

  profiles: 

    active: 

    - dev

---

server: 

  port: 9527

   

spring: 

  profiles: dev

  application:

    name: ds-zuul

    

eureka: 

  instance: 

    hostname: ds-zuul:9527.com #冒号后面必须要有空格

  client: 

    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中

    fetch-registry: false #不通过eureka获取注册信息

    service-url: 

      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

---


server: 

  port: 9527

   

spring: 

  profiles: test

  application:

    name: ds-zuul

    

eureka: 

  instance: 

    hostname: ds-zuul:9527.com #冒号后面必须要有空格

  client: 

    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中

    fetch-registry: false #不通过eureka获取注册信息

    service-url: 

      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
